package com.artarkatesoft.artsfgspring5mvcrest.api.v1.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
@ApiModel(value = "customer", description = "Customer object")
public class CustomerDTO {

    @ApiModelProperty(value = "This is First Name", required = true)
    @JsonProperty("firstname")
    private String firstName;
    @ApiModelProperty(value = "This is Last Name")
    @JsonProperty("lastname")
    private String lastName;
    @ApiModelProperty(value = "This is Customer Url",allowEmptyValue = true,notes = "will be generated by API and send back")
    @JsonProperty("customer_url")
    private String customerUrl;

}
